### ISSUE TITLE
[OptionEx] Issue when other plugin add new option command

### ISSUE THREAD

**Issue by RyanBram** [nz-prism/RPG-Maker-MZ#1]
Hi, Developer.
Thank you for your wonderful collection of plugins, which make it possible to create visual novels with RPG Maker MZ.

I'm currently trying to use OptionEx where this plugin makes the Option Window even nicer. I'm currently having an issue, when your plugin is combined with [Sasuke KANNAZUKI's BattleSystemSelectable.js](https://forum.tkool.jp/index.php?threads/%E3%80%90%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%80%91%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E7%94%BB%E9%9D%A2%E3%81%8B%E3%82%89tpb%E3%82%A6%E3%82%A7%E3%82%A4%E3%83%88%E3%81%A8%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%82%92%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E5%8F%AF%E8%83%BD%E3%81%AB.4386/).

Here is how it looks:

1. If the OptionEx plugin is placed before BattleSystemSelectable.js the new option will be placed after "Reset to Default" which visually is not very good.
![Before](https://user-images.githubusercontent.com/4508389/154843439-2976e3ac-f1a6-460b-920b-76a31a0fe2cd.jpg)

2. If the OptionEx plugin is placed after BattleSystemSelectable.js we need to scroll the window to select "Reset to Default"
![After](https://user-images.githubusercontent.com/4508389/154843382-3d030ea1-1d13-4e47-81e4-b774a548617c.jpg)

Then I have a suggestion that OptionEx also provide an "Option Window Height" plugin parameter in addition to the already existing "Option Window Width". And also an option to choose other Windowskin for Option Window will be nice to have.

Thank you very much for your support.

**Comment by nz-prism** [comment]
Hi RyanBram,

Thank you so much for your feedback!

I could reproduce your issue and corrected it by updating the plugin ver. **1.2.3**.
Please check it out!

Basically, the window height stretches based on the number of option items. However, the number of max items was previously limited only "16", which was the main cause of the issue. Now it calculates the max number based on the screen height and the item height. I think it automatically solves the issue but if not, try lowering the plugin parameters "**Option Item Height**", "**Font Size**" and "**Default Command Offset**".

By updating the plugin and place it under **BattleSystemSelectable.js**, the screen will be like;

![スクリーンショット 2022-02-21 17 27 45](https://user-images.githubusercontent.com/83767318/154919139-adaabdfe-a580-456f-8b94-65b8cee78a54.png)

If you have any questions, feel free to ask me!

Thanks,
nz_prism

**Comment by RyanBram** [comment]
Hi, nz-prism.

Thanks a lot for the quick fix.

I've downloaded the latest version of OptionEx and confirmed that this plugin is compatible with BattleSystemSelectable.js. However I still find a little issue if I set the window width to 812px, while I also set the "UI Area Width" in "System 2" at 812px, where touch control is blocking the option window as shown below:
![Option](https://user-images.githubusercontent.com/4508389/155189613-1c8ec2ba-0a59-443e-ac9a-5d92394c5372.jpg)

My suggestion is to lower the options window a little bit down as the main menu for the placement of touch controls.
![Menu](https://user-images.githubusercontent.com/4508389/155189654-18651610-9f54-424f-b026-12d3f6327cff.jpg)

Although it seems that with position adjustment, the number of options displayed will exceed the screen so scrolling is still necessary. But I see this is neater than the previous version.

ご支援ありがとうございました
Ryan Bram

**Comment by nz-prism** [comment]
Hi Ryan Bram,

Thank you for the feedback again!

I've updated the plugin **1.3.0** to add a plugin parameter "**Place Option Window Under Buttons**";
![スクリーンショット 2022-02-24 17 47 26](https://user-images.githubusercontent.com/83767318/155492123-69225d8a-b293-4ef8-8051-f01a0b256d27.png)

If it's set true, the window is placed under the buttons;
![スクリーンショット 2022-02-24 17 45 37](https://user-images.githubusercontent.com/83767318/155492262-006655c0-4f55-4ceb-aed5-6d55a76051da.png)

If false;
![スクリーンショット 2022-02-24 17 46 23](https://user-images.githubusercontent.com/83767318/155492308-793bb7d5-8485-4acd-a81b-ae93640f2659.png)

I believe this update will solve the issue. Check it out!

Note if the window is placed under the buttons, the window height decreases instead. If it doesn't accommodate all the items, lower "**Option Item Height**".


> I am sorry for the lack of clear explanation. What I mean by windowskin is the plugin parameter that allows the windowskin used by OptionEx to be different from the windowskin in other menu scenes. This makes OptionEx look unique and less generic.

Sorry for misunderstanding. That's an interesting suggestion but I'd say it's difficult to implement since it must conflict against the existing option item "**Windowskin**".
But thank you, your suggestions are always welcomed!


If you have any questions, please let me know.


こちらこそありがとうございます！
nz_prism

**Comment by RyanBram** [comment]
Hi, nz-prism.
Sorry that I'm very slow in replying to your messages.

I've tried the last update of option-ex.js and I can say that the "Place Option Window Under Buttons" option works very well. However there is a slight issue that I encountered, where "Option Window Width" has a different output than "UI Area Width".

In the "UI Area Width" I set the value to 812, but if I enter the same value in the "Option Window Width" then the result is the option window is wider than it should be, so I have to lower the value in the "Option Window Width" to 804 to be the same like 812 in "UI Area Width".

Then I found the window height is also different from what I set in "UI Area Height" which is 624.

ご清聴ありがとうございました。

Ryan

**Comment by nz-prism** [comment]
Hi Ryan,

Actually, it's a matter of a "preference". Currently I don't set any upper limit to "Option Window Width", which brings your issue.

The width of RMMZ standard windows which stretch from the left-end to the right-end, such as a status window, has a padding;

![スクリーンショット 2022-03-05 8 57 11](https://user-images.githubusercontent.com/83767318/156857652-bec3a1b2-7168-44f2-a463-9a161e13466b.png)

See, the windows is a little smaller than the screen width. The formula is;

`Graphics.boxWidth = uiAreaWidth - 8`
`Graphics.boxHeight = uiAreaHeight - 8`

In your case, 812 - 8 = **804** is the "boxWidth".

I can set an upper limit to the option window width by boxWidth, which will be like;

![スクリーンショット 2022-03-05 9 09 13](https://user-images.githubusercontent.com/83767318/156858490-81db1a5b-9fa9-49f5-930c-cb6a3df6406f.png)

However, you can get this image even with the current version by manually specifying the same value as "boxWidth" to Option Window Width. If I limit the window width, it prevents users to set the window without a padding;

![スクリーンショット 2022-03-05 9 10 02](https://user-images.githubusercontent.com/83767318/156858606-6ce59def-cee9-442a-8673-107d6d108352.png)

I don't think there are many users who want it but there MIGHT be one!
I'm afraid to say but I ask you to manually set **804** to Option Window Width since I don't want to limit any preferences of users.


ありがとうございます,
nz_prism

**Comment by RyanBram** [comment]
Hi, nz-prism, (^_^)

I understand about your design regarding this plugin.
Since it is by design, for me it is no longer an issue, after all, my problem is very easy to solve.

Thus I will close this Github Issue. But before I really close this issue, I'd like to ask your permission to open a few more issues to give me some ideas regarding your other plugins. Because thanks to your plugins, I'm so happy to be able to create visual novels with RPG Maker MZ without the need for any other software. Where previously I relied on plugins from [Lunatlazur](https://github.com/Lunatlazur/rpgmakermv-plugins/tree/develop/build) in RPG Maker MV.

Would you mind if I open another issue?

Thank you very much.
Ryan.

**Comment by nz-prism** [comment]
Hi Ryan,

Thank you!

> Thus I will close this Github Issue. But before I really close this issue, I'd like to ask your permission to open a few more issues to give me some ideas regarding your other plugins. Because thanks to your plugins, I'm so happy to be able to create visual novels with RPG Maker MZ without the need for any other software. Where previously I relied on plugins from [Lunatlazur](https://github.com/Lunatlazur/rpgmakermv-plugins/tree/develop/build) in RPG Maker MV.
> 
> Would you mind if I open another issue?

Not at all! I always welcome your feedbacks.
My plugin is so "young" that it might have a lot of potential issues. Your feedbacks bring it up!


Thank you for using my plugin and filing this issue. If you have any questions, feel free to ask me!

どういたしまして,
nz_prism
